#!/usr/bin/env bash

if [ "$1" = "go" -a "$2" != "-h" ]
then
    nvidia-docker exec -it "$2" bash
else
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    python "${DIR}/gpu-containers.py" $@
fi